
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          username: light
          password: 12345
          url: jdbc:mysql://180.76.179.65/newDay
        note:
          type: com.alibaba.druid.pool.DruidDataSource
          username: light
          password: 12345
          url: jdbc:mysql://180.76.179.65/cloudnote
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/ ,file:D:/DataDispose/
mybatis-plus:
  mapper-locations: ["classpath*:/mapper/**/*.xml"]
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  file:
    path: log
debug: false



uploadFileDir: D:/DataDispose
tempUploadFileDir: /temp
