
server:
  port: 7070

spring:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource  #代表使用druid类型的数据源
          username: root
          password: jsjk*888
          url: jdbc:mysql://192.9.200.50:3306/strongest_information_database?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
#        note:
#          type: com.alibaba.druid.pool.DruidDataSource
#          username: light
#          password: 12345
#          url: jdbc:mysql://180.76.179.65/cloudnote
        point:
          type: com.alibaba.druid.pool.DruidDataSource  #代表使用druid类型的数据源
          username: root
          password: jsjk*888
          url: jdbc:mysql://192.9.200.50:3306/strongest_information_database?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
        maintain:
          type: com.alibaba.druid.pool.DruidDataSource  #代表使用druid类型的数据源
          username: root
          password: jsjk*888
          url: jdbc:mysql://192.9.200.50:3306/maintain?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/ ,file:D:/DataDispose/,file:D:/upload/
mybatis-plus:
  mapper-locations: ["classpath*:/mapper/**/*.xml"]
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  file:
    path: log

debug: false

staticPrefix: /static
uploadFileDir: D:/DataDispose
tempUploadFileDir: /temp
imageDir: /image


